### PR TITLE
wip removing all default imports slowing down imports and showing unr…

### PR DESCRIPTION
**Pull request by topherbuckley**
…elated errors

Would also like to remove src/beachbot/utils/__init__py contents with this as well. confirming dependencies tomorrow with Jeffrey.

### CODE REVIEW

**Comment by topherbuckley** [comment]
This might break some things, but importing all submodules by default leads to several issues:
1. Errors for things like missing but unnecessary dependencies (i.e. torchvision, Jetson.GPIO, etc.). These things can be tested on the Jetson, but forcing the import of specific parts of the library only when necessary isolates them such that errors will only occur related to relevant code. (e.g. I don't want to see an error about Jetson.GPIO when I'm pushing something related to huggingface). 
2. Its super slow. (10-30 secs depending on which Pc I'm using). 

I can test this on the Jetson for the nicegui controller and see what errors come up and generate quickfixes for them. I'll add those to this PR after testing.

**Comment by jeffreyfq** [comment]
1. Errors can be avoided with try catch as it was before. We can test if a package is available and skip initalization.
2. Yes thats annoying, I may check if it is avoidable to do this slow init right after import

**Comment by topherbuckley** [comment]
I'm proposing not to import everything always, but only import what is necessary to a particular file. What is the advantage of the try catch? From my perspective this is just hiding errors making this code harder to debug and understand. If you want to use code that depends on these optional dependencies (e.g. Jetson.GPIO) then you can still use that code on the Jetson without issue. You get an error only on systems try to use Jetson.GPIO but don't have it. That is what I would expect to happen. I don't want to show no errors when I have an import error. 

I'm in the robot room now. I can test these against the Jetson to see what relative imports would need to exist to get the nice_gui app to work.

**Comment by topherbuckley** [comment]
I just refactored the nice_gui app to allow for relative imports using this. Works just fine. See the refactor commit above:
https://github.com/okinawa-ai-beach-robot/python-interface/pull/25/commits/515a9eaa388f16d7cb2e4b48306f7a64c383a53b

**Comment by topherbuckley** [comment]
fixes for gui controller given in `gui_init_refactor` for reference, though @jeffreyfq has been modifying that a lot recently, so won't include that here. He is welcome to use it for reference if useful.

**Pull request merged**
